<?xml version="1.0" encoding="ASCII"?>

<!-- oks-data version 2.0 -->


<!DOCTYPE oks-data [
  <!ELEMENT oks-data (info, (include)?, (comments)?, (obj)+)>
  <!ELEMENT info EMPTY>
  <!ATTLIST info
      name CDATA #REQUIRED
      type CDATA #REQUIRED
      num-of-items CDATA #REQUIRED
      oks-format CDATA #FIXED "extended"
      oks-version CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      creation-time CDATA #REQUIRED
      last-modified-by CDATA #REQUIRED
      last-modified-on CDATA #REQUIRED
      last-modification-time CDATA #REQUIRED
  >
  <!ELEMENT include (file)+>
  <!ELEMENT file EMPTY>
  <!ATTLIST file
      path CDATA #REQUIRED
  >
  <!ELEMENT comments (comment)+>
  <!ELEMENT comment EMPTY>
  <!ATTLIST comment
      creation-time CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      author CDATA #REQUIRED
      text CDATA #REQUIRED
  >
  <!ELEMENT obj (attr | rel)*>
  <!ATTLIST obj
      class CDATA #REQUIRED
      id CDATA #REQUIRED
  >
  <!ELEMENT attr (#PCDATA)*>
  <!ATTLIST attr
      name CDATA #REQUIRED
      type (bool|s8|u8|s16|u16|s32|u32|s64|u64|float|double|date|time|string|uid|enum|class|-) "-"
      num CDATA "-1"
  >
  <!ELEMENT rel (#PCDATA)*>
  <!ATTLIST rel
      name CDATA #REQUIRED
      num CDATA "-1"
  >
]>

<oks-data>

<info name="" type="" num-of-items="59" oks-format="extended" oks-version="v* built &quot;Apr  2 2014&quot;" created-by="isolov" created-on="lxplus015" creation-time="20030411T183347" last-modified-by="isolov" last-modified-on="pcatd79.cern.ch" last-modification-time="20140416T073111"/>

<include>
 <file path="oks/gui/oks_data_editor.schema.xml"/>
</include>


<obj class="Class" id="BaseApplication">
 <attr name="Name" type="string">"BaseApplication"</attr>
 <attr name="Generic Pixmap File" type="string">"application.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-application.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"application.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"application_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="1">
  "LogicalPartitions"
 </attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="2">
  "InitializationDependsFrom"
  "ShutdownDependsFrom"
 </attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Binary">
 <attr name="Name" type="string">"Binary"</attr>
 <attr name="Generic Pixmap File" type="string">"binary.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-binary.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"binary.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"binary_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="1">
  "BelongsTo"
 </attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="BinaryFile">
 <attr name="Name" type="string">"BinaryFile"</attr>
 <attr name="Generic Pixmap File" type="string">"binary.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-binary.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"binary.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"binary_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Computer">
 <attr name="Name" type="string">"Computer"</attr>
 <attr name="Generic Pixmap File" type="string">"computer.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-computer.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"computer.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"computer_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="ComputerSet">
 <attr name="Name" type="string">"ComputerSet"</attr>
 <attr name="Generic Pixmap File" type="string">"computer-set.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-computer-set.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"computer-set.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"computer-set_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Crate">
 <attr name="Name" type="string">"Crate"</attr>
 <attr name="Generic Pixmap File" type="string">"crate.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-crate.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"crate.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"crate_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="1">
  "BelongsTo"
 </attr>
 <attr name="Icon Title" type="string">"@ID@ (@CLASS@)"</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Detector">
 <attr name="Name" type="string">"Detector"</attr>
 <attr name="Generic Pixmap File" type="string">"detector.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-detector.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"detector.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"detector_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="1">
  "IsPartOf"
 </attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="1">
  "Dual Relationship" "Detector_to_Detector"
 </rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="HW_System">
 <attr name="Name" type="string">"HW_System"</attr>
 <attr name="Generic Pixmap File" type="string">"hw-system.xpm"</attr>
 <attr name="Used Pixmap File" type="string">""</attr>
 <attr name="Icon Bitmap File" type="string">"hw-system.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"hw-system_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="JarFile">
 <attr name="Name" type="string">"JarFile"</attr>
 <attr name="Generic Pixmap File" type="string">"jar.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-jar.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"binary.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"binary_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="1">
  "BelongsTo"
 </attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Module">
 <attr name="Name" type="string">"Module"</attr>
 <attr name="Generic Pixmap File" type="string">"module.xpm"</attr>
 <attr name="Used Pixmap File" type="string">""</attr>
 <attr name="Icon Bitmap File" type="string">"module.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"module_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="2">
  "IsPartOf"
  "ControlsDFC"
 </attr>
 <attr name="Icon Title" type="string">"@ID@ (@CLASS@) "</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="NetworkInterface">
 <attr name="Name" type="string">"NetworkInterface"</attr>
 <attr name="Generic Pixmap File" type="string">"kcmpci.xpm"</attr>
 <attr name="Used Pixmap File" type="string">""</attr>
 <attr name="Icon Bitmap File" type="string">"module.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"module_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="2">
  "IsPartOf"
  "ControlsDFC"
 </attr>
 <attr name="Icon Title" type="string">"@ID@ (@CLASS@) "</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Parameter">
 <attr name="Name" type="string">"Parameter"</attr>
 <attr name="Generic Pixmap File" type="string">"environment.xpm"</attr>
 <attr name="Used Pixmap File" type="string">""</attr>
 <attr name="Icon Bitmap File" type="string">"environment.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"environment_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Partition">
 <attr name="Name" type="string">"Partition"</attr>
 <attr name="Generic Pixmap File" type="string">"partition.xpm"</attr>
 <attr name="Used Pixmap File" type="string">""</attr>
 <attr name="Icon Bitmap File" type="string">"partition.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"partition_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Partition (Control Tree)">
 <attr name="Name" type="string">"Partition"</attr>
 <attr name="Generic Pixmap File" type="string">"partition.xpm"</attr>
 <attr name="Used Pixmap File" type="string">""</attr>
 <attr name="Icon Bitmap File" type="string">"partition.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"partition_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">0</attr>
 <attr name="Relationships" type="string" num="2">
  "Segments"
  "OnlineInfrastructure"
 </attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="RM_Resource">
 <attr name="Name" type="string">"RM_Resource"</attr>
 <attr name="Generic Pixmap File" type="string">"rm-resource.xpm"</attr>
 <attr name="Used Pixmap File" type="string">""</attr>
 <attr name="Icon Bitmap File" type="string">"rm-resource.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"rm-resource_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Rack">
 <attr name="Name" type="string">"Rack"</attr>
 <attr name="Generic Pixmap File" type="string">"rack.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-rack.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"rack.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"rack_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Resource (Control Tree)">
 <attr name="Name" type="string">"ResourceBase"</attr>
 <attr name="Generic Pixmap File" type="string">"resource.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-resource.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"resource.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"resource_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">0</attr>
 <attr name="Relationships" type="string" num="1">
  "Contains"
 </attr>
 <attr name="Icon Title" type="string">"@ID@"</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="ResourceBase">
 <attr name="Name" type="string">"ResourceBase"</attr>
 <attr name="Generic Pixmap File" type="string">"resource.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-resource.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"resource.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"resource_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="RunControl">
 <attr name="Name" type="string">"RunControlApplication"</attr>
 <attr name="Generic Pixmap File" type="string">"application.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-application.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"application.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"application_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">0</attr>
 <attr name="Relationships" type="string" num="1">
  "children"
 </attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="2">
  "InitializationDependsFrom"
  "ShutdownDependsFrom"
 </attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="RunTagList">
 <attr name="Name" type="string">"RunTagList"</attr>
 <attr name="Generic Pixmap File" type="string">"run-tag-list.xpm"</attr>
 <attr name="Used Pixmap File" type="string">""</attr>
 <attr name="Icon Bitmap File" type="string">"run-tag-list.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"run-tag-list_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="SW_Package">
 <attr name="Name" type="string">"SW_Package"</attr>
 <attr name="Generic Pixmap File" type="string">"sw_repository.xpm"</attr>
 <attr name="Used Pixmap File" type="string">""</attr>
 <attr name="Icon Bitmap File" type="string">"sw_repository.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"sw_repository_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="1">
  "SW_Objects"
 </attr>
 <rel name="Dual Relationships" num="1">
  "Dual Relationship" "SW_Repository_to_SW_Object"
 </rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Script">
 <attr name="Name" type="string">"Script"</attr>
 <attr name="Generic Pixmap File" type="string">"script.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-script.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"script.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"script_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="1">
  "BelongsTo"
 </attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="1">
  "ImplementedBy"
 </attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="1">
  "Init Attribute Value" "Authors of Script "
 </rel>
</obj>

<obj class="Class" id="Segment">
 <attr name="Name" type="string">"Segment"</attr>
 <attr name="Generic Pixmap File" type="string">"segment.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-segment.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"segment.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"segment_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Segment (Control Tree)">
 <attr name="Name" type="string">"Segment"</attr>
 <attr name="Generic Pixmap File" type="string">"segment.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-segment.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"segment.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"segment_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">0</attr>
 <attr name="Relationships" type="string" num="2">
  "Segments"
  "Resources"
 </attr>
 <attr name="Icon Title" type="string">"@ID@"</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Class" id="Tag">
 <attr name="Name" type="string">"Tag"</attr>
 <attr name="Generic Pixmap File" type="string">"tag.xpm"</attr>
 <attr name="Used Pixmap File" type="string">"used-tag.xpm"</attr>
 <attr name="Icon Bitmap File" type="string">"tag.xbm"</attr>
 <attr name="Icon Mask Bitmap File" type="string">"tag_mask.xbm"</attr>
 <attr name="Show All Attributes" type="bool">1</attr>
 <attr name="Attributes" type="string" num="0"></attr>
 <attr name="Show All Relationships" type="bool">1</attr>
 <attr name="Relationships" type="string" num="0"></attr>
 <attr name="Icon Title" type="string">""</attr>
 <attr name="Remove From Used" type="string" num="0"></attr>
 <rel name="Dual Relationships" num="0"></rel>
 <rel name="Initialize Attributes" num="0"></rel>
</obj>

<obj class="Dual Relationship" id="Detector_to_Detector">
 <attr name="Direct" type="string">"ConsistsOf"</attr>
 <attr name="Reverse" type="string">"IsPartOf"</attr>
</obj>

<obj class="Dual Relationship" id="SW_Repository_to_SW_Object">
 <attr name="Direct" type="string">"SW_Objects"</attr>
 <attr name="Reverse" type="string">"BelongsTo"</attr>
</obj>

<obj class="Init Attribute Value" id="Authors of Script ">
 <attr name="Attribute Name" type="string">"Authors"</attr>
 <attr name="Environment Variables" type="string" num="6">
  "XXX"
  "MAILSERV_GEM"
  "MAILSERV_NAME"
  "MAILSERV_USER"
  "USER"
  "LOGNAME"
 </attr>
</obj>

<obj class="Main" id="Top">
 <attr name="Used objects" type="enum">"Show-as-used"</attr>
 <attr name="Root relationship" type="string">"Segments"</attr>
 <rel name="Root class">"Class" "Partition"</rel>
</obj>

<obj class="Window" id="Control Tree">
 <attr name="Title" type="string">"Control Tree"</attr>
 <rel name="Items" num="3">
  "Window Class" "Partition (Control Tree)"
  "Window Class" "Segment (Control Tree)"
  "Window Class" "Resource (Control Tree)"
 </rel>
</obj>

<obj class="Window" id="Hardware">
 <attr name="Title" type="string">"Hardware"</attr>
 <rel name="Items" num="9">
  "Window Class" "HW_System"
  "Window Class" "Detector"
  "Window Separator" "Top-Level"
  "Window Class" "Rack"
  "Window Class" "Crate"
  "Window Class" "Computer"
  "Window Class" "ComputerSet"
  "Window Class" "Module"
  "Window Class" "NetworkInterface"
 </rel>
</obj>

<obj class="Window" id="Partition">
 <attr name="Title" type="string">"Partition"</attr>
 <rel name="Items" num="6">
  "Window Class" "Partition"
  "Window Class" "Segment"
  "Window Class" "ResourceBase"
  "Window Separator" "Top-Level"
  "Window Class" "BaseApplication"
  "Window Class" "Parameter"
 </rel>
</obj>

<obj class="Window" id="Software Repository">
 <attr name="Title" type="string">"Software Repository"</attr>
 <rel name="Items" num="9">
  "Window Class" "SW Repository"
  "Window Class" "Tag"
  "Window Separator" "Top-Level"
  "Window Class" "Script"
  "Window Class" "Binary"
  "Window Class" "JarFile"
  "Window Separator" "Top-Level"
  "Window Class" "RM_Resource"
  "Window Class" "Parameter (no top-level objs)"
 </rel>
</obj>

<obj class="Window Class" id="BaseApplication">
 <attr name="Top Level Name" type="string">"BaseApplications"</attr>
 <attr name="Show on top level" type="enum">"with-used-menu"</attr>
 <attr name="Use to create top-level objects" type="bool">1</attr>
 <attr name="Show in new" type="bool">1</attr>
 <attr name="Shown with children" type="enum">"none"</attr>
 <attr name="Root relationship name" type="string">""</attr>
 <rel name="Graphical Class">"Class" "BaseApplication"</rel>
</obj>

<obj class="Window Class" id="Binary">
 <attr name="Top Level Name" type="string">"Unlinked\nprograms"</attr>
 <attr name="Show on top level" type="enum">"without-used-menu"</attr>
 <attr name="Use to create top-level objects" type="bool">1</attr>
 <attr name="Show in new" type="bool">1</attr>
 <attr name="Shown with children" type="enum">"none"</attr>
 <attr name="Root relationship name" type="string">""</attr>
 <rel name="Graphical Class">"Class" "Binary"</rel>
</obj>

<obj class="Window Class" id="BinaryFile">
 <attr name="Top Level Name" type="string">"Binary\nFile"</attr>
 <attr name="Show on top level" type="enum">"without-used-menu"</attr>
 <attr name="Use to create top-level objects" type="bool">1</attr>
 <attr name="Show in new" type="bool">1</attr>
 <attr name="Shown with children" type="enum">"none"</attr>
 <attr name="Root relationship name" type="string">""</attr>
 <rel name="Graphical Class">"Class" "BinaryFile"</rel>
</obj>

<obj class="Window Class" id="Computer">
 <attr name="Top Level Name" type="string">"Computers"</attr>
 <attr name="Show on top level" type="enum">"with-used-menu"</attr>
 <attr name="Use to create top-level objects" type="bool">1</attr>
 <attr name="Show in new" type="bool">1</attr>
 <attr name="Shown with children" type="enum">"none"</attr>
 <attr name="Root relationship name" type="string">""</attr>
 <rel name="Graphical Class">"Class" "Computer"</rel>
</obj>

<obj class="Window Class" id="ComputerSet">
 <attr name="Top Level Name" type="string">"Computer Sets"</attr>
 <attr name="Show on top level" type="enum">"with-used-menu"</attr>
 <attr name="Use to create top-level objects" type="bool">1</attr>
 <attr name="Show in new" type="bool">1</attr>
 <attr name="Shown with children" type="enum">"none"</attr>
 <attr name="Root relationship name" type="string">""</attr>
 <rel name="Graphical Class">"Class" "ComputerSet"</rel>
</obj>

<obj class="Window Class" id="Crate">
 <attr name="Top Level Name" type="string">"Non-detector\ncrates"</attr>
 <attr name="Show on top level" type="enum">"with-used-menu"</attr>
 <attr name="Use to create top-level objects" type="bool">1</attr>
 <attr name="Show in new" type="bool">1</attr>
 <attr name="Shown with children" type="enum">"none"</attr>
 <attr name="Root relationship name" type="string">""</attr>
 <rel name="Graphical Class">"Class" "Crate"</rel>
</obj>

<obj class="Window Class" id="Detector">
 <attr name="Top Level Name" type="string">"Detectors"</attr>
 <attr name="Show on top level" type="enum">"with-used-menu"</attr>
 <attr name="Use to create top-level objects" type="bool">1</attr>
 <attr name="Show in new" type="bool">1</attr>
 <attr name="Shown with children" type="enum">"none"</attr>
 <attr name="Root relationship name" type="string">""</attr>
 <rel name="Graphical Class">"Class" "Detector"</rel>
</obj>

<obj class="Window Class" id="HW_System">
 <attr name="Top Level Name" type="string">"Computers"</attr>
 <attr name="Show on top level" type="enum">"with-used-menu"</attr>
 <attr name="Use to create top-level objects" type="bool">1</attr>
 <attr name="Show in new" type="bool">1</attr>
 <attr name="Shown with children" type="enum">"none"</attr>
 <attr name="Root relationship name" type="string">""</attr>
 <rel name="Graphical Class">"Class" "HW_System"</rel>
</obj>

<obj class="Window Class" id="JarFile">
 <attr name="Top Level Name" type="string">"Unlinked\jar files"</attr>
 <attr name="Show on top level" type="enum">"without-used-menu"</attr>
 <attr name="Use to create top-level objects" type="bool">1</attr>
 <attr name="Show in new" type="bool">1</attr>
 <attr name="Shown with children" type="enum">"none"</attr>
 <attr name="Root relationship name" type="string">""</attr>
 <rel name="Graphical Class">"Class" "JarFile"</rel>
</obj>

<obj class="Window Class" id="Module">
 <attr name="Top Level Name" type="string">"Modules"</attr>
 <attr name="Show on top level" type="enum">"without-used-menu"</attr>
 <attr name="Use to create top-level objects" type="bool">1</attr>
 <attr name="Show in new" type="bool">1</attr>
 <attr name="Shown with children" type="enum">"none"</attr>
 <attr name="Root relationship name" type="string">""</attr>
 <rel name="Graphical Class">"Class" "Module"</rel>
</obj>

<obj class="Window Class" id="NetworkInterface">
 <attr name="Top Level Name" type="string">"Network Interfaces"</attr>
 <attr name="Show on top level" type="enum">"without-used-menu"</attr>
 <attr name="Use to create top-level objects" type="bool">1</attr>
 <attr name="Show in new" type="bool">1</attr>
 <attr name="Shown with children" type="enum">"none"</attr>
 <attr name="Root relationship name" type="string">""</attr>